config/routes.rb
Frontend::Application.routes.draw do
  get "/homepage" => redirect("/")
  get "/search.json" => redirect { |params,req| "/api/search.json?q=#{CGI.escape(req.query_parameters['q'] || '')}" }
  get "/search" => "search#index", as: :search
  post "/search" => proc { [405, {}, ["Method Not Allowed"]] } # Prevent non-GET requests for /search blowing up in the publication handlers below
  get "/search/opensearch" => "search#opensearch"
  get "/browse.json" => redirect("/api/tags.json?type=section&root_sections=true")
  get "/browse" => "browse#index", to: "browse#index"
  get "/browse/:section.json" => redirect("/api/tags.json?type=section&parent_id=%{section}")
  get "/browse/:section", as: "browse", to: "browse#section"
  get "/browse/:section/:sub_section.json" => redirect("/api/with_tag.json?tag=%{section}%%2F%{sub_section}")
  get "/browse/:section/:sub_section", as: "browse", to: "browse#sub_section"

  # new business browse page
  get "/business" => "browse#section", :section => "business"

  # Crude way of handling the situation described at
  # http://stackoverflow.com/a/3443678
  get "*path.gif", to: proc {|env| [404, {}, ["Not Found"]] }

  get "/help", to: "help#index"
  get "/tour", to: "root#tour"

  get '/foreign-travel-advice', to: "travel_advice#index", as: :travel_advice
  post "/foreign-travel-advice" => proc { [405, {}, ["Method Not Allowed"]] } # Prevent POST requests for /foreign-travel-advice blowing up in the publication handlers below
  with_options(:to => "travel_advice#country") do |country|
    country.get "/foreign-travel-advice/:country_slug/print", :format => :print
    country.get "/foreign-travel-advice/:country_slug(/:part)", :as => :travel_advice_country
  end

  # Campaign pages.
  with_options :format => false do |routes|
    routes.get "/ukwelcomes", :to => "campaign#uk_welcomes"
  end

  # Jobssearch form override (English and Welsh variants)
  constraints(:slug => /(jobsearch|chwilio-am-swydd)/) do
    get "/:slug.json"      => redirect("/api/%{slug}.json")
    get "/:slug(.:format)" => "root#jobsearch"
  end

  # Transaction finished pages
  constraints(slug: /(transaction-finished|driving-transaction-finished)/) do
    get "/:slug.json"      => redirect("/api/%{slug}.json")
    get "/:slug(.:format)" => "root#legacy_completed_transaction"
  end

  get ":slug/y(/*responses)" => "simple_smart_answers#flow", :as => :smart_answer_flow

  with_options(as: "publication", to: "root#publication") do |pub|
    pub.get "*slug", slug: %r{(done|help)/.+}
    pub.get ":slug/print", format: :print
    pub.get ":slug/:part/:interaction", as: :licence_authority_action

    # Our approach to providing local transaction information currently
    # requires that this support get and post
    pub.match ":slug(/:part)", :via => [:get, :post]
  end

  root :to => 'root#index', :via => :get
end

app/controllers/search_controller.rb
require "slimmer/headers"

class SearchController < ApplicationController

  before_filter :setup_slimmer_artefact, only: [:index]
  before_filter :set_expiry
  helper_method :ministerial_departments, :other_organisations, :selected_tab

  rescue_from GdsApi::BaseError, with: :error_503

  def index
    @search_term = params[:q]

    if @search_term.blank?
      render action: 'no_search_term' and return
    else
      @streams = []

      if params[:organisation].present? || params[:sort].present?
        government_results = retrieve_government_results(@search_term, params[:organisation], params[:sort])
        unfiltered_government_results = retrieve_government_results(@search_term)
      else
        government_results = retrieve_government_results(@search_term)
        unfiltered_government_results = government_results
      end

      if raw_mainstream_results(@search_term)["spelling_suggestions"]
        @spelling_suggestion = raw_mainstream_results(@search_term)["spelling_suggestions"].first
      end

      detailed_results = retrieve_detailed_guidance_results(@search_term)
      # hackily downweight detailed results to prevent them swamping mainstream results
      adjusted_detailed_results = multiply_result_scores(detailed_results, 0.8)

      @streams << SearchStream.new(
        "services-information",
        "Services and information",
        merge_result_sets(retrieve_mainstream_results(@search_term), adjusted_detailed_results)
      )
      @streams << SearchStream.new(
        "government",
        "Departments and policy",
        government_results
      )

      # This needs to be done before top result extraction, otherwise the
      # result count needs to incorporate the top result size.
      @result_count = @streams.map { |s| s.results.size }.sum

      top_result_sets = @streams.reject { |s| s.key == "government" }.map(&:results)
      # Hackily downweight government results to stop them from swamping mainstream in top results
      top_result_sets << multiply_result_scores(unfiltered_government_results, 0.6)

      all_results_ordered = merge_result_sets(*top_result_sets)
      @top_results = all_results_ordered[0..2]
      @top_results.each do |result_to_remove|
        @streams.detect do |stream|
          stream.results.delete(result_to_remove)
        end
      end
    end

    fill_in_slimmer_headers(@result_count)

    @active_stream = active_stream(@streams)

    # We want to show the tabs if there's a filter in place
    # because there might be results with the filter turned off, but you can't
    # do that if the filter-form/tabs aren't displayed
    if (@result_count == 0) && params[:organisation].blank?
      render action: 'no_results' and return
    end
  end

  protected

  def raw_mainstream_results(term)
    @_raw_mainstream_results ||= begin
      Frontend.mainstream_search_client.search(term)
    end
  end

  def retrieve_mainstream_results(term)
    res = raw_mainstream_results(term)
    res["results"].map { |r| SearchResult.new(r) }
  end


  def retrieve_detailed_guidance_results(term)
    res = Frontend.detailed_guidance_search_client.search(term)
    res["results"].map { |r| SearchResult.new(r) }
  end

  def retrieve_government_results(term, organisation = nil, sort = nil)
    extra_parameters = {}
    extra_parameters[:organisation_slug] = organisation if organisation
    extra_parameters[:sort] = sort if sort.present?
    res = Frontend.government_search_client.search(term, extra_parameters)
    res["results"].map { |r| GovernmentResult.new(r) }
  end

  def merge_result_sets(*result_sets)
    # .sort_by(&:es_score) will return it back to front
    result_sets.flatten(1).sort_by(&:es_score).reverse
  end

  def fill_in_slimmer_headers(result_count)
    set_slimmer_headers(
      result_count: result_count,
      format:       "search",
      section:      "search",
      proposition:  "citizen"
    )
  end

  def setup_slimmer_artefact
    set_slimmer_dummy_artefact(:section_name => "Search", :section_link => "/search")
  end

  # The tab that the user has clicked on. We should remember this.
  def selected_tab
    # This list would be more robust if it were built from the streams
    tabs =  %w{ government-results services-information-results }
    tabs.include?(params[:tab]) ? params[:tab] : nil
  end

  # The tab that should be selected.
  # If the user has selected a tab, use that one.
  # Otherwise, select the first tab with results.
  # If there are no results, select the first tab.
  def active_stream(streams)
    active_stream = streams.detect do |stream|
      stream_key_as_tab_name = "#{stream.key}-results"
      if selected_tab
        stream_key_as_tab_name == selected_tab
      else
        stream.anything_to_show?
      end
    end
    active_stream || streams.first
  end

  def organisations
    @_organisations ||= Frontend.organisations_search_client.organisations["results"] || []
  end

  MINISTERIAL_DEPARTMENT_TYPE = "Ministerial department"
  def ministerial_departments
    organisations.select do |organisation|
      organisation["organisation_type"] == MINISTERIAL_DEPARTMENT_TYPE
    end.sort_by { |organisation| organisation["title"] }
  end

  def other_organisations
    organisations.reject do |organisation|
      organisation["organisation_type"] == MINISTERIAL_DEPARTMENT_TYPE
    end.sort_by { |organisation| organisation["title"] }
  end

  def multiply_result_scores(result_set, multiply_by)
    result_set.map do |result|
      result.result["es_score"] = result.result["es_score"] * multiply_by
      result
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def show_tabs?(streams)
    streams.any?(&:anything_to_show?) || params[:organisation]
  end

  def display_organisations(organisations)
    organisations.map do |organisation|
      if organisation["acronym"] && (organisation["acronym"] != organisation["title"])
        content_tag("abbr", title: organisation["title"]) do
          organisation["acronym"]
        end
      else
        organisation["title"] || organisation["slug"]
      end
    end.join(", ").html_safe
  end
end

app/views/search/_detailed_guidance_result.html.erb
<li class="section-<%= result.section %> type-<%= result.format %>">
  <%= render partial: "result_debug_score", locals: { result: result } %>

  <h3>
    <a href="<%= result.link %>" title="View <%= result.title %>">
      <%= result.title %>
    </a>
  </h3>

    <p class="meta crumbtrail">
      <span class="visuallyhidden">Part of </span>
      <span class="section"><%= result.formatted_section_name %></span>
      <% if result.subsection %><span class="visuallyhidden">, </span><span class="subsection"><%= result.formatted_subsection_name %></span><% end %>
      <% if result.subsubsection %><span class="visuallyhidden">, </span><span class="subsubsection"><%= result.formatted_subsubsection_name %></span><% end %>
    </p>
  <p><%= result.description %></p>
</li>

app/views/search/_form.html.erb
<form action="/search" method="get" accept-charset="utf-8" class="search-header search-header-2 js-search-hash" role="search">
  <%= render partial: "hidden_form_tags" %>
  <%= hidden_field_tag(:organisation, params[:organisation]) if params[:organisation] %>
  <%= hidden_field_tag(:sort, params[:sort]) if params[:sort] %>
  <div class="searchfield">
    <fieldset class="search-input">
      <label for="search-main">
        <%- if @search_term.present? -%>
          <h1>Search results for <span class="visuallyhidden">&ldquo;<%= @search_term %>&rdquo;</span ></h1>
        <%- else -%>
          <h1>Search GOV.UK</h1>
        <%- end -%>
      </label>
      <input type="search" name="q" value="<%= @search_term %>" id="search-main" />
    </fieldset>
    <fieldset class="search-submit">
      <button type="submit" class="button">Search</button>
    </fieldset>
  </div>
  <% if @spelling_suggestion %>
    <fieldset class="spelling-suggestion">
      <p>Did you mean <%= link_to "#{@spelling_suggestion}", search_path(q: @spelling_suggestion, tab: params[:tab], spelling_suggestion: params[:spelling_suggestion]) %>
      </p>
    </fieldset>
  <% end %>
</form>

app/views/search/_general_result.html.erb
<li class="section-<%= result.section %> type-<%= result.format %>">
  <%= render partial: "result_debug_score", locals: { result: result } %>

    <h3>
      <a href="<%= result.link %>" title="View <%= result.title %>">
        <%= result.title %>
      </a>
    </h3>
    <% if result.section %>
      <p class="meta crumbtrail">
        <span class="visuallyhidden">Part of </span>
        <span class="section"><%= result.formatted_section_name %></span>
        <% if result.subsection %><span class="visuallyhidden">, </span><span class="subsection"><%= result.formatted_subsection_name %></span><% end %>
        <% if result.subsubsection %><span class="visuallyhidden">, </span><span class="subsubsection"><%= result.formatted_subsubsection_name %></span><% end %>
      </p>
    <% end %>
    <p><%= result.description %></p>
</li>

app/views/search/_government_filter.html.erb
<form id="government-filter" method="get" action="" class="search-filter">
  <%= hidden_field_tag(:q, params[:q]) %>
  <%= render partial: "hidden_form_tags" %>
  <label for="organisation-filter">Show results from </label>
  <select name="organisation" id="organisation-filter">
    <option value="">All organisations</option>
    <optgroup label="Ministerial departments">
      <% ministerial_departments.each do |organisation| %>
        <option value="<%= organisation["slug"] %>" <%= (params[:organisation] == organisation["slug"]) ? "selected=selected" : "" %>>
          <%= organisation["title"] %>
        </option>
      <% end %>
    </optgroup>
    <optgroup label="Others">
      <% other_organisations.each do |organisation| %>
        <option value="<%= organisation["slug"] %>" <%= (params[:organisation] == organisation["slug"]) ? "selected=selected" : "" %>>
          <%= organisation["title"] %>
        </option>
      <% end %>
    </optgroup>
  </select>

  <fieldset class="sort-by">
    <h3>Sort by</h3>
    <label>
      <%= radio_button_tag "sort", "", params[:sort].blank? %>
      relevance
    </label>
    <label>
      <%= radio_button_tag "sort", "public_timestamp", params[:sort] == "public_timestamp" %>
      date
    </label>
  </fieldset>

  <button type="submit" class="button">
    Refresh results
  </button>
</form>

app/views/search/_hidden_form_tags.html.erb
<%= hidden_field_tag(:debug_score, params[:debug_score]) if params[:debug_score] %>
<%= hidden_field_tag(:spelling_suggestion, params[:spelling_suggestion]) if params[:spelling_suggestion] %>
<%= hidden_field_tag :tab, selected_tab if selected_tab %>

app/views/search/_inside_government_result.html.erb
<li class="section-<%= result.section %> type-<%= result.format %>">
  <%= render partial: "result_debug_score", locals: { result: result } %>

  <h3>
    <a href="<%= result.link %>" title="View <%= result.title %>">
      <%= result.title %>
    </a>
  </h3>

  <ul class="attributes">
    <% if result.public_timestamp.present? %>
      <li>
        <span class="visuallyhidden">Published on: </span>
        <%= result.display_timestamp %>
      </li>
    <% end %>
    <% if result.display_type.present? %>
      <li>
        <%= result.display_type %>
      </li>
    <% end %>
    <% if result.has_organisations? %>
      <li>
        <span class="visuallyhidden">Departments: </span>
        <%= display_organisations(result.organisations) %>
      </li>
    <% end %>
    <% if result.has_world_locations? %>
      <li>
        <span class="visuallyhidden">Location: </span>
        <%= result.display_world_locations %>
      </li>
    <% end %>
  </ul>

  <% case result.format %>
  <% when 'corporate_information_page' then %>
    <p class="attributes">Corporate information</p>
    <p><%= result.display_a_description %></p>
  <% when 'document_series' then %>
    <p class="attributes">Document series</p>
    <p><%= result.display_a_description %></p>
  <% when 'minister' then %>
    <p><%= result.display_a_description %></p>
    <ul class="sections">
      <li><a href="<%= result.link %>#responsibilities">Responsibilities</a></li>
      <li><a href="<%= result.link %>#current-role-holder">Current role holder</a></li>
    </ul>
  <% when 'organisation' then %>
    <p>The home of <%= result.title %> on GOV.UK. <%= result.display_a_description %></p>
    <% if result.display_links? %>
      <ul class="sections">
        <li><a href="<%= result.link %>#topics">What we do</a></li>
        <li><a href="<%= result.link %>#policies">Policies</a></li>
        <li><a href="<%= result.link %>#org-contacts">Contact details</a></li>
        <li><a href="<%= result.link %>#ministers">Ministers</a></li>
      </ul>
    <% end %>
  <% when 'person' then %>
    <p><%= result.display_a_description %></p>
    <ul class="sections">
      <li><a href="<%= result.link %>#biography">Biography</a></li>
      <li><a href="<%= result.link %>#current-roles">Roles</a></li>
    </ul> 
  <% when 'world_location' then %>
    <p><%= result.display_a_description %></p>
    <ul class="sections">
      <li><a href="<%= result.link %>#worldwide-priorities">Priorities</a></li>
      <li><a href="<%= result.link %>#organisations">Organisations in <%= result.title %></a></li>
    </ul> 
  <% when 'worldwide_organisation' then %>
    <p><%= result.display_a_description %></p>
    <ul class="sections">
      <li><a href="<%= result.link %>#our-services">Services</a></li>
      <li><a href="<%= result.link %>#contact-us">Contact details</a></li>
    </ul>
  <% else %>
    <p><%= result.display_a_description %></p>
  <% end %>
</li>

app/views/search/_no_results.html.erb
<div class="no-results">
  <h2>
    <% if context.present? %>
      No results in <%= context %> for &ldquo;<%= @search_term %>&rdquo;
    <% else %>
      No results for &ldquo;<%= @search_term %>&rdquo;
    <% end %>
  </h2>

  <p>Please try</p>

  <ul>
    <li>Searching again using different words</li>
    <li>Browsing from the <a href="/">GOV.UK home page</a></li>
    <li>Visiting the <a href="/help">help pages</a> if you need more assistance</li>
  </ul>

  <h3>Older content</h3>
  <p>
    Not all department publications from before May 2010 were migrated to
    GOV.UK. To find publications from before May 2010 try searching
    <a href="http://webarchive.nationalarchives.gov.uk/adv_search/?<%= { query: @search_term }.to_param %>">The National Archives</a>.
  </p>
</div>

app/views/search/_recommended_link_result.html.erb
<li class="type-guide external">
  <%= render partial: "result_debug_score", locals: { result: result } %>

  <h3>
    <a href="<%= result.link %>" title="View <%= result.title %>" rel="external">
      <%= result.title %>
    </a>
  </h3>
  <p class="meta">
    <span class="visuallyhidden">Part of </span>
    <span class="url"><%= result.display_link %></span>
  </p>
  <p><%= result.description %></p>
</li>

app/views/search/_result.html.erb
<% if result.format == "recommended-link" %>
  <%= render partial: "recommended_link_result", locals: { result: result } %>
<% elsif (result.format == 'detailed_guidance' && result.section) %>
  <%= render partial: "detailed_guidance_result", locals: { result: result } %>
<% elsif result.is_a?(GovernmentResult) && result.format %>
  <%= render partial: "inside_government_result", locals: { result: result } %>
<% else %>
  <%= render partial: "general_result", locals: { result: result } %>
<% end %>

app/views/search/_result_debug_score.html.erb
  <% if params[:debug_score] %>
    <span style="color: red;">
      <small>
        <%= result.es_score %>
        &nbsp;
        <%= result.format %>
        &nbsp;
        <%= result.is_a?(GovernmentResult) ? "government" : "" %>
      </small>
    </span>
  <% end %>

app/views/search/index.html.erb
<% content_for :body_classes do %>search<% end %>


<main id="content" role="main" class="group search ancillary">
  <%= render partial: 'form' %>

  <% if @top_results %>
    <div id="top-results">
      <h2 class="visuallyhidden">Top result</h2>
      <ul class="results-list">
        <% @top_results.each_with_index do |top_result, index| %>
        <%= render partial: "result", locals: { result: top_result } %>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div id="search-results-tabs" class="shouty-tabs">
    <h2 class="visuallyhidden">All results</h2>
    <% if show_tabs?(@streams) %>
      <div class="search-navigation js-tabs">
      <% if @streams.count == 2 %>
        <ul id="search-index-navigation" class="two-tabs">
      <% else %>
        <ul id="search-index-navigation">
      <% end %>
        <% @streams.each do |stream| %>
          <li <% if @active_stream == stream %>class="active"<% end %>>
            <a href="#<%= stream.key %>-results">
              <%= stream.title.html_safe %>
            </a>
          </li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <% if show_tabs?(@streams) %>
      <div class="search-container group js-tab-content tab-content ">
        <% @streams.each do |stream| %>
          <div id="<%= stream.key %>-results" class="js-tab-pane tab-pane <%= stream.results.size == 1 ? ' single-item-pane' : '' %>">
          <div class="filters">
            <% if stream.key == "government" %>
              <%= render partial: "government_filter" %>
            <% end %>
          </div>
          <div class="results">
          <% if stream.results.size > 0 %>
            <ul class="results-list internal-links">
              <%= render collection: stream.results, partial: "result" %>
            </ul>
          <% end %>
          <% unless stream.anything_to_show? %>
            <%= render partial: "no_results", locals: { context: stream.title } %>
          <% end %>
          </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</main>

<h3 class="visuallyhidden">No more results for <span class="visuallyhidden">&ldquo;<%= @search_term %>&rdquo;</span>. <a href="#search-main">Try a different search?</a></h3>

<% content_for :extra_headers do %>
  <link rel="alternate" type="application/json" href="/api/search.json?q=<%= @search_term %>">
<% end %>

<% content_for :title, "#{@search_term} - Search - GOV.UK" %>

app/views/search/no_results.html.erb
<% content_for :body_classes do %>search<% end %>


<main id="content" role="main" class="group ancillary search no-results">
  <%= render partial: 'form' %>

  <div class="search-container group">

  <%= render partial: "no_results", locals: { context: nil } %>

  </div>
</main>
<% content_for :title, "#{@search_term} - Search - GOV.UK" %>

app/views/search/no_search_term.html.erb
<% content_for :body_classes do %>search<% end %>


<main id="content" role="main" class="group ancillary search search-launcher">
  <%= render partial: 'form' %>
</main>

<% content_for :title, "Search - GOV.UK" %>