config/routes.rb
Frontend::Application.routes.draw do
  get "/homepage" => redirect("/")
  get "/search.json" => redirect { |params,req| "/api/search.json?q=#{CGI.escape(req.query_parameters['q'] || '')}" }
  get "/search" => "search#index", as: :search
  post "/search" => proc { [405, {}, ["Method Not Allowed"]] } # Prevent non-GET requests for /search blowing up in the publication handlers below
  get "/search/opensearch" => "search#opensearch"
  get "/browse.json" => redirect("/api/tags.json?type=section&root_sections=true")
  get "/browse" => "browse#index", to: "browse#index"
  get "/browse/:section.json" => redirect("/api/tags.json?type=section&parent_id=%{section}")
  get "/browse/:section", as: "browse", to: "browse#section"
  get "/browse/:section/:sub_section.json" => redirect("/api/with_tag.json?tag=%{section}%%2F%{sub_section}")
  get "/browse/:section/:sub_section", as: "browse", to: "browse#sub_section"

  # new business browse page
  get "/business" => "browse#section", :section => "business"

  # Crude way of handling the situation described at
  # http://stackoverflow.com/a/3443678
  get "*path.gif", to: proc {|env| [404, {}, ["Not Found"]] }

  get "/help", to: "help#index"
  get "/tour", to: "root#tour"

  get '/foreign-travel-advice', to: "travel_advice#index", as: :travel_advice
  post "/foreign-travel-advice" => proc { [405, {}, ["Method Not Allowed"]] } # Prevent POST requests for /foreign-travel-advice blowing up in the publication handlers below
  with_options(:to => "travel_advice#country") do |country|
    country.get "/foreign-travel-advice/:country_slug/print", :format => :print
    country.get "/foreign-travel-advice/:country_slug(/:part)", :as => :travel_advice_country
  end

  # Campaign pages.
  with_options :format => false do |routes|
    routes.get "/ukwelcomes", :to => "campaign#uk_welcomes"
  end

  # Jobssearch form override (English and Welsh variants)
  constraints(:slug => /(jobsearch|chwilio-am-swydd)/) do
    get "/:slug.json"      => redirect("/api/%{slug}.json")
    get "/:slug(.:format)" => "root#jobsearch"
  end

  # Transaction finished pages
  constraints(slug: /(transaction-finished|driving-transaction-finished)/) do
    get "/:slug.json"      => redirect("/api/%{slug}.json")
    get "/:slug(.:format)" => "root#legacy_completed_transaction"
  end

  get ":slug/y(/*responses)" => "simple_smart_answers#flow", :as => :smart_answer_flow

  with_options(as: "publication", to: "root#publication") do |pub|
    pub.get "*slug", slug: %r{(done|help)/.+}
    pub.get ":slug/print", format: :print
    pub.get ":slug/:part/:interaction", as: :licence_authority_action

    # Our approach to providing local transaction information currently
    # requires that this support get and post
    pub.match ":slug(/:part)", :via => [:get, :post]
  end

  root :to => 'root#index', :via => :get
end

app/controllers/travel_advice_controller.rb
class TravelAdviceController < ApplicationController

  before_filter(:only => [:country]) { validate_slug_param(:country_slug) }
  before_filter(:only => [:country]) { validate_slug_param(:part) if params[:part] }

  def index
    set_expiry

    artefact = fetch_artefact('foreign-travel-advice')
    set_slimmer_artefact_headers(artefact, :format => 'travel-advice')

    @publication = TravelAdviceIndexPresenter.new(artefact)

    respond_to do |format|
      format.html
      format.atom { set_expiry(5.minutes) }
      # TODO: Doing a static redirect to the API URL here means that an API call
      #       and a variety of other logic will have been executed unnecessarily.
      #       We should move this to the top of the method or out to routes.rb for
      #       efficiency.
      format.json { redirect_to "/api/foreign-travel-advice.json" }
    end
  end

  def country
    set_expiry(5.minutes)

    @country = params[:country_slug].dup
    @edition = params[:edition]

    @publication = fetch_publication_for_country(@country)

    tags = @publication.artefact.to_hash["tags"]
    section_tag = tags.find {|t| t["details"]["type"] == "section" }

    combined_tags = slimmer_section_tag_for_details(
      :section_name => "Foreign travel advice",
      :section_link => "/foreign-travel-advice"
    ).merge("parent" => section_tag)

    if section_tag.present?
      tags[tags.index(section_tag)] = combined_tags
    else
      tags << combined_tags
    end

    set_slimmer_artefact_headers(@publication.artefact.to_hash.merge('tags' => tags))

    I18n.locale = :en # These pages haven't been localised yet.

    if params[:part].present?
      @publication.current_part = params[:part]
      unless @publication.current_part
        redirect_to travel_advice_country_path(@country) and return
      end
    end

    respond_to do |format|
      format.html
      format.atom
      format.print do
        set_slimmer_headers template: "print"
      end
    end
  rescue RecordNotFound
    error 404
  end

  private

  def fetch_publication_for_country(country)
    artefact = fetch_artefact("foreign-travel-advice/" + country, params[:edition])
    TravelAdviceCountryPresenter.new(artefact)
  end
end

app/helpers/travel_advice_helper.rb
require 'htmlentities'

module TravelAdviceHelper

  def group_by_initial_letter(countries)
    countries.group_by do |country|
      country.name[0] if country and country.name
    end
  end

  def readable_time(time)
    time = DateTime.parse(time) unless time.respond_to?(:strftime)
    time.strftime("%e %B %Y")
  end

  def format_atom_change_description(text)
    # Encode basic entities([<>&'"]) as named, the rest as decimal
    simple_format(HTMLEntities.new.encode(text, :basic, :decimal))
  end
end

app/views/travel_advice/_country_summary.html.erb
<% if publication.parts.present? then %>
<header>
  <h1>Summary</h1>
</header>
<% end %>

<ul class="country-metadata">
  <li><div class="label">Still current at:</div> <%= Date.today.strftime("%e %B %Y") %></li>
  <li><div class="label">Updated:</div> <%= publication.last_reviewed_or_updated_at.strftime("%e %B %Y") %></li>

  <%# Don't show change description for countries that haven't been updated before this was
      added to this view as the descriptions aren't very useful to users. %>
  <%- if publication.updated_at > Date.civil(2013, 04, 22) -%>
    <li><%= simple_format publication.change_description %></li>
  <%- end -%>
</ul>

<% if publication.alert_status.present? %>
  <div class="application-notice help-notice">
    <% publication.alert_status.each do |alert| %>
      <p><%= raw t("travel_advice.alert_status.#{alert}") %></p>
    <% end %>
  </div>
<% end %>

<% if publication.image %>
  <p>
    <img src="<%= publication.image.web_url %>" alt="" />
  </p>
<% end %>
<% if publication.document %>
  <div class="form-download">
  <p>
    <a href="<%= publication.document.web_url %>">Download map (PDF)</a>
  </p>
  </div>
<% end %>

<%= raw publication.summary %>

app/views/travel_advice/_travel_advice_navigation.html.erb
<aside>
  <div class="inner">
    <nav role="navigation" class="page-navigation" aria-label="parts to this guide">
      <% @publication.navigation_parts.each_slice(parts_group_size(@publication.navigation_parts)).with_index do |parts,i| %>
        <ol<%= " start=\"#{parts_group_size(@publication.navigation_parts) + 1}\"".html_safe if i == 1 %>>
          <% parts.each do |nav_part| %>
            <% if (@publication.current_part.nil? && nav_part[:slug] == nil) || (@publication.current_part && @publication.current_part.slug == nav_part[:slug]) %>
              <li class="active">
                <span class="part-title"><%= nav_part[:title] %></span>
                <% if nav_part[:slug].nil? %>
                  <span class="part-description">Current travel advice</span>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to part_path(@publication.slug, nav_part[:slug], @edition), :title => nav_part[:title] do %>
                  <span class="part-title"><%= nav_part[:title] %></span>
                  <% if nav_part[:slug].nil? %>
                    <span class="part-description">Current travel advice</span>
                  <% end %>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ol>
      <% end %>
    </nav>

    <section class="subscriptions">
      <h1 class="visuallyhidden">Subscriptions</h1>
      <ul> 
        <li><a href="https://public.govdelivery.com/accounts/UKGOVUK/subscriber/topics?qsp=TRAVEL" class="email-alerts" title="Subscribe to email alerts" rel="external">Email alerts</a></li>
        <li><%= link_to "RSS", publication_path(@publication.slug, format: "atom"), :class => "feed", :title => "Subscribe via RSS" %></li>
      </ul>
    </section>

  </div>
  
</aside>

app/views/travel_advice/country.html.erb
<main id="content" role="main" class="group <%= @publication.parts.present? ? "multi" : "single" %>-page">

  <header class="page-header group">
    <div>
      <h1><span>Foreign travel advice </span><%= @publication.country['name'] %></h1>
    </div>
    <a class="skip-to-related" href="#related"><%= t 'common.not_what_youre_looking_for' %> ↓</a>
  </header>

  <div class="article-container group">
    <%= render :partial => "travel_advice_navigation" if @publication.parts.present? %>

    <article role="article" class="group">
      <div class="inner">

        <% if @publication.current_part %>
          <header>
            <h1><%= @publication.current_part.title %></h1>
          </header>

          <%= raw @publication.current_part.body %>
        <% else %><%# The summary page %>
          <%= render :partial => "country_summary", :locals => {:publication => @publication} %>
        <% end %>

        <div class="print-link"><%= link_to t('formats.guide.printer_friendly_page'), publication_path(@publication.slug, :part => 'print', :edition => @edition), rel: "nofollow" %></div>
      </div>

    </article>

    <div id="report-a-problem"></div>
  </div>

</main>

<div id="related-items"></div>

<% content_for :extra_headers do %>
  <link rel="alternate" type="application/json" href="<%= publication_api_path(@publication, :edition => @edition) %>" />
  <%= auto_discovery_link_tag :atom, travel_advice_country_path(@publication.country['slug'], :format => :atom),
    :title => "Recent updates for #{@publication.country['name']}" %>
  <%- if @publication.current_part and @publication.has_previous_part? -%>
    <link rel="prev" href="<%= part_path(@publication.slug, @publication.previous_part.slug, @edition) %>" />
  <%- end -%>
  <%- if @publication.current_part and @publication.has_next_part? -%>
    <link rel="next" href="<%= part_path(@publication.slug, @publication.next_part.slug, @edition) %>" />
  <%- end -%>
<% end %>

app/views/travel_advice/country.print.erb
<header>
  <h1><%= @publication.country['name'] %> travel advice</h1>
</header>

<article id="summary">
  <%= render :partial => 'country_summary', :locals => {:publication => @publication }, :formats => ['html'] %>
</article>
<% (@publication.parts || []).each do |part| %>
  <article id="<%= part.slug %>">
    <header>
      <h1><%= part.title %></h1>
    </header>

    <%= raw part.body %>
  </article>
<% end %>

app/views/travel_advice/index.html.erb
<% content_for :extra_headers do %>
  <%= javascript_include_tag "views/travel-advice.js" %>
  <link rel="alternate" type="application/json" href="<%= publication_api_path(@publication, :edition => @edition) %>" />
  <%= auto_discovery_link_tag :atom, travel_advice_path(:format => :atom), :title => "Recent updates" %>
<% end %>

<section id="content" class="group">
  <header class="page-header group">
    <div>
      <h1><%= @publication.title %></h1>
    </div>
  </header>

  <div class="article-container group">
    <article role="article" class="group">
      <div class="inner">

        <section id="country-filter">
          <form>
            <fieldset>
              <h1>Which country or territory are you looking for?</h1>
              <label for="country">Country or territory</label>
              <input id="country" name="country" type="text" />
            </fieldset>
          </form>
        </section>
        <section class="subscriptions">
          <h1 class="visuallyhidden">Subscriptions</h1>
          <ul>
            <li><a href="https://public.govdelivery.com/accounts/UKGOVUK/subscriber/topics?qsp=TRAVEL" class="email-alerts" rel="external" title="Subscribe to email alerts">email alerts</a></li>
            <li><%= link_to "RSS", publication_path(@publication.slug, format: "atom"), :class => "feed", :title => "Subscribe via RSS" %></li>
          </ul>
        </section>
        <section class="countries-wrapper">
          <h1>Countries or territories</h1>       
          <p class="country-count">
            <span class="js-filter-count"><%= @publication.countries.length %></span>
            <span class="visuallyhidden">Countries or territories</span>
          </p>
          <% group_by_initial_letter(@publication.countries).each do |initial,countries| %>
          <div id="<%= initial %>" class="list">
            <h2><span class="visuallyhidden">Countries starting with </span><%= initial %></h2>
            <ul class="countries">
              <% countries.each do |country| %>
                <li data-synonyms='<%= country.synonyms ? country.synonyms.join("|") : "" %>'><%= link_to country.name, travel_advice_country_path(country.identifier) %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
        </section>
      </div>
    </article>

    <div id="report-a-problem"></div>
  </div>
</section>

<div id="related-items"></div>